# Generated by Django 5.0.1 on 2024-01-24 14:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Priority')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, verbose_name='Department')),
                ('depadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depadmin', to=settings.AUTH_USER_MODEL, verbose_name='Department Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.department')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Date')),
                ('createdbyUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdbyuser', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.department', verbose_name='Department')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.priority', verbose_name='Priority')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.product', verbose_name='Product')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.status', verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followupnote', models.CharField(max_length=1000, verbose_name='Comment')),
                ('followup_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to=settings.AUTH_USER_MODEL, verbose_name='Assign to')),
                ('followup_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_user', to=settings.AUTH_USER_MODEL, verbose_name='Comment by')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.ticket')),
            ],
        ),
    ]
